### ISSUE TITLE
Read variables from somewhere other than environment

### ISSUE THREAD

**Issue by RealOrangeOne** [FrictionlessPortals/spotify-oauth#1]
Currently it's not possible to set the `redirect_uri` when converting a callback into a token with anything other than an environment variable. It would be useful to read this from variables in memory (namely so they can be populated at request time).

Many of the client configuration variables also aren't scoped, so `CLIENT_ID` could mean any client. It would be useful if they were prefixed with `SPOTIFY_`.

https://github.com/FrictionlessPortals/spotify-oauth/blob/master/src/lib.rs#L400

**Comment by FrictionlessPortals** [comment]
The user could create a ``SpotifyConfig`` structure with their ``CLIENT_ID`` and ``REDIRECT_URL`` as fields. 

The creation of the ``SpotifyConfig`` could also have functions to initially populate them from a ``.env`` file or from the environment itself with prefixing, as mentioned, to prevent overlapping environment variables and to distinguish them from others.

This structure will then become a required argument for functions that require ``redirect_url`` and other variables required at request time.
