### ISSUE TITLE
use of undeclared type or module `open`

### ISSUE THREAD

**Issue by vervaekejonathan** [FrictionlessPortals/spotify-oauth#4]
In the example, what is 'open' referring too?

 `open::that(auth_url)?;`

**Comment by FrictionlessPortals** [comment]
``open::that(auth_url)?`` refers to [this](https://docs.rs/open/1.4.0/open/fn.that.html) function in the [open](https://crates.io/crates/open) crate. I will update the comment on that function call to include a reference to the crate mentioned above.
